-- 00001_CORE: EXTENSÕES, TIPOS E FUNÇÕES BASE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Enums de Domínio
CREATE TYPE order_status AS ENUM ('PENDING_PAYMENT', 'PAID', 'PROCESSING', 'PARTIALLY_FULFILLED', 'FULFILLED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED');
CREATE TYPE payment_status AS ENUM ('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'CHARGEBACK');
CREATE TYPE reservation_status AS ENUM ('ACTIVE', 'COMMITTED', 'RELEASED', 'EXPIRED', 'CANCELLED');
CREATE TYPE fulfillment_status AS ENUM ('PENDING', 'PROCESSING', 'READY', 'SHIPPED', 'DELIVERED', 'CANCELLED');
CREATE TYPE ledger_entry_type AS ENUM ('SALE_CREDIT', 'PRODUCT_COST', 'SHIPPING_COST', 'GATEWAY_FEE', 'PUB_FEE', 'REFUND_DEBIT', 'CHARGEBACK_DEBIT', 'CHARGEBACK_FEE', 'PAYOUT', 'ADJUSTMENT');
-- Modificado: Adicionado SHIPMENT
CREATE TYPE inventory_movement_type AS ENUM ('RECEIPT', 'RESERVE', 'RELEASE', 'COMMIT', 'SHIPMENT', 'RETURN', 'LOSS');

-- Função automática para updated_at (Somente tabelas mutáveis)
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

